export const constellations = [
  {
    name: "Andromeda",
    shape: "The Andromeda constellation has a unique shape that looks like a sprawling figure with its arms stretched out, forming either a 'V' or 'W' in the night sky.",
    brightestStars: ["α Andromedae", "β Andromedae", "γ Andromedae"],
    interestingObjects: ["Andromeda Galaxy", "Blue Snowball Nebula"],
    value: "and",
    info: "The constellation Andromeda is named after Andromeda, a princess in Greek mythology who was chained to a rock by the sea to be eaten by a sea monster. Perseus, a hero, slew the sea monster and rescued Andromeda. They were married and lived happily ever after. The constellation was named by the Ancient Greek astronomer Ptolemy in the 2nd century AD. Andromeda is best visible from Earth during the autumn and winter months in the Northern Hemisphere.",
    rightAscension: "00h 42m 44.00s",
    declination: "+41° 16′ 00.0″",
    area: "722.0 square degrees",
    imageSrc: "../images/andromeda.png"
  },
  {
    name: "Antlia",
    shape: "The Antlia constellation is relatively faint and does not have any prominent stars or distinctive shape. It appears as a collection of faint stars scattered across the sky.",
    brightestStars: [],
    interestingObjects: ["NGC 2997 (Sculptor Galaxy)", "Antlia Dwarf (Antlia Dwarf Galaxy)"],
    value: "ant",
    info: "The Antlia constellation is named after the air pump invented by French physicist Denis Papin in the 17th century. It was introduced by the French astronomer Abbé Nicolas Louis de Lacaille in the 18th century. Antlia is relatively faint and does not have any prominent stars or a distinctive shape. It appears as a collection of faint stars scattered across the sky. The best time to observe Antlia from Earth is during the spring and summer months in the Southern Hemisphere.",
    rightAscension: "10h 22m 25.80s",
    declination: "-32° 30′ 17.0″",
    area: "239.0 square degrees",
    imageSrc: "../images/antlia.png"
  },
  {
    name: "Apus",
    shape: "The Apus constellation does not have a prominent shape and consists of relatively faint stars. It appears as a scattered group of stars in the night sky.",
    brightestStars: [],
    interestingObjects: ["IC 4499 (Apus Globular Cluster)"],
    value: "apu",
    info: "The Apus constellation is named after the bird-of-paradise species called Apus, which are known for their distinctive appearance. Apus is best visible from Earth during the summer months in the Southern Hemisphere.",
    rightAscension: "14h 47m 32.10s",
    declination: "-76° 46′ 05.0″",
    area: "206.3 square degrees",
    imageSrc: "../images/apus.png"
  },
  {
    name: "Aquarius",
    shape: "The Aquarius constellation represents a person pouring water from a jug. It is often associated with the Greek mythological figure of Ganymede, the cupbearer of the gods.",
    brightestStars: ["β Aquarii", "γ Aquarii", "η Aquarii"],
    interestingObjects: ["Helix Nebula", "Saturn Nebula"],
    value: "aqu",
    info: "The Aquarius constellation is associated with the water-bearer from Greek mythology, often identified as Ganymede. It was one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Aquarius is best visible from Earth during the autumn months in the Northern Hemisphere and the spring months in the Southern Hemisphere.",
    rightAscension: "22h 38m 00.00s",
    declination: "-14° 29′ 00.0″",
    area: "980.0 square degrees",
    imageSrc: "../images/aquarius.png"
  },
  {
    name: "Aquila",
    shape: "The Aquila constellation resembles an eagle with outstretched wings. It is often associated with the Roman mythological figure of the god Jupiter, who transformed into an eagle.",
    brightestStars: ["α Aquilae", "β Aquilae", "γ Aquilae"],
    interestingObjects: ["Eagle Nebula", "Sagittarius Dwarf Irregular Galaxy"],
    value: "aquil",
    info: "The Aquila constellation represents an eagle in various mythologies, including the Roman mythological figure of Jupiter, who transformed into an eagle to carry his lover Ganymede to Mount Olympus. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Aquila is best visible from Earth during the summer months in the Northern Hemisphere.",
    rightAscension: "19h 04m 00.00s",
    declination: "+05° 30′ 00.0″",
    area: "652.5 square degrees",
    imageSrc: "../images/aquila.png"
  },
  {
    name: "Ara",
    shape: "The Ara constellation represents the altar used in ancient Roman and Greek religious ceremonies. It is often associated with the Greek mythological figure of the centaur Chiron.",
    brightestStars: ["β Arae", "γ Arae", "δ Arae"],
    interestingObjects: ["NGC 6193 (Ara Cluster)", "Eta Carinae Nebula"],
    value: "ara",
    info: "The Ara constellation represents the altar in ancient Roman and Greek mythology, often associated with the centaur Chiron. It was one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Ara is best visible from Earth during the winter months in the Southern Hemisphere.",
    rightAscension: "17h 24m 00.00s",
    declination: "-55° 30′ 00.0″",
    area: "237.1 square degrees",
    imageSrc: "../images/ara.png"
  },
  {
    name: "Aries",
    shape: "The Aries constellation represents the ram from Greek mythology, specifically the golden ram that rescued Phrixus and Helle.",
    brightestStars: ["α Arietis", "β Arietis", "γ Arietis"],
    interestingObjects: ["Triangulum Galaxy", "Sheratan (β Arietis)"],
    value: "ari",
    info: "The Aries constellation represents the ram from Greek mythology, particularly the golden ram that saved Phrixus and Helle from being sacrificed. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Aries is best visible from Earth during the autumn months in the Northern Hemisphere.",
    rightAscension: "02h 07m 00.00s",
    declination: "+18° 30′ 00.0″",
    area: "441.4 square degrees",
    imageSrc: "../images/aries.png"
  },
  {
    name: "Auriga",
    shape: "The Auriga constellation resembles a charioteer or a shepherd holding a goat.",
    brightestStars: ["Capella (α Aurigae)", "β Aurigae", "γ Aurigae"],
    interestingObjects: ["Flaming Star Nebula", "Messier 36 (Star Cluster)"],
    value: "aur",
    info: "The Auriga constellation represents a charioteer or a shepherd holding a goat. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Auriga is best visible from Earth during the winter months in the Northern Hemisphere.",
    rightAscension: "05h 16m 00.00s",
    declination: "+43° 00′ 00.0″",
    area: "657.4 square degrees",
    imageSrc: "../images/auriga.png"
  },
  {
    name: "Bootes",
    shape: "The Bootes constellation represents a herdsman or a plowman chasing the nearby Ursa Major constellation.",
    brightestStars: ["Arcturus (α Bootis)", "β Bootis", "γ Bootis"],
    interestingObjects: ["Arcturus (α Bootis)", "M3 (Globular Cluster)"],
    value: "boo",
    info: "The Bootes constellation represents a herdsman or a plowman, often associated with Greek mythology figures such as Arcas or Icarius. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Bootes is best visible from Earth during the spring and summer months in the Northern Hemisphere.",
    rightAscension: "14h 00m 00.00s",
    declination: "+30° 00′ 00.0″",
    area: "907.0 square degrees",
    imageSrc: "../images/bootes.png"
  },
  {
    name: "Caelum",
    shape: "The Caelum constellation does not have any prominent shape and is made up of relatively faint stars.",
    brightestStars: ["α Caeli", "β Caeli", "γ Caeli"],
    interestingObjects: ["NGC 1679 (Open Cluster)", "ESO 205-AS033 (Spiral Galaxy)"],
    value: "cae",
    info: "The Caelum constellation is a faint constellation located in the southern celestial hemisphere. It was introduced by the French astronomer Nicolas Louis de Lacaille in the 18th century. Caelum is best visible from Earth during the summer months in the Southern Hemisphere.",
    rightAscension: "04h 32m 00.00s",
    declination: "-37° 00′ 00.0″",
    area: "125.7 square degrees",
    imageSrc: "../images/caelum.png"
  },
  {
    name: "Camelopardalis",
    shape: "The Camelopardalis constellation represents a giraffe. It is a large but faint constellation located in the northern celestial hemisphere.",
    brightestStars: ["β Camelopardalis", "γ Camelopardalis", "δ Camelopardalis"],
    interestingObjects: ["IC 342 (Spiral Galaxy)", "Kemble's Cascade (Asterism)"],
    value: "cam",
    info: "The Camelopardalis constellation represents a giraffe. It is one of the 88 modern constellations and was introduced in the 17th century. Camelopardalis is best visible from Earth during the winter months in the Northern Hemisphere.",
    rightAscension: "06h 00m 00.00s",
    declination: "+70° 00′ 00.0″",
    area: "757.7 square degrees",
    imageSrc: "../images/camelopardalis.png"
  },
  {
    name: "Cancer",
    shape: "The Cancer constellation represents a crab. It is one of the twelve constellations of the zodiac.",
    brightestStars: ["β Cancri", "α Cancri", "γ Cancri"],
    interestingObjects: ["Beehive Cluster (M44)", "Crab Nebula (M1)"],
    value: "cnc",
    info: "The Cancer constellation represents a crab and is one of the twelve constellations of the zodiac. It is best visible from Earth during the winter months in the Northern Hemisphere.",
    rightAscension: "08h 45m 00.00s",
    declination: "+20° 00′ 00.0″",
    area: "506.0 square degrees",
    imageSrc: "../images/cancer.png"
  },
  {
    name: "Canes Venatici",
    shape: "The Canes Venatici constellation represents two hunting dogs.",
    brightestStars: ["α Canum Venaticorum (Cor Caroli)", "β Canum Venaticorum", "δ Canum Venaticorum"],
    interestingObjects: ["Whirlpool Galaxy (M51)", "Canes Venatici I (Dwarf Galaxy)"],
    value: "cvn",
    info: "The Canes Venatici constellation represents two hunting dogs. It was introduced by the Polish astronomer Johannes Hevelius in the 17th century. Canes Venatici is best visible from Earth during the spring months in the Northern Hemisphere.",
    rightAscension: "13h 10m 00.00s",
    declination: "+40° 00′ 00.0″",
    area: "465.0 square degrees",
    imageSrc: "../images/canesvenatici.png"
  },
  {
    name: "Canis Major",
    shape: "The Canis Major constellation represents a great dog.",
    brightestStars: ["Sirius (α Canis Majoris)", "β Canis Majoris", "δ Canis Majoris"],
    interestingObjects: ["Great Orion Nebula (M42)", "Open Cluster NGC 2362"],
    value: "cma",
    info: "The Canis Major constellation represents a great dog, often associated with the mythological dog Laelaps or the dog of Orion. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Canis Major is best visible from Earth during the winter months in the Northern Hemisphere.",
    rightAscension: "06h 30m 00.00s",
    declination: "-20° 00′ 00.0″",
    area: "380.1 square degrees",
    imageSrc: "../images/canismajor.png"
  },
  {
    name: "Canis Minor",
    shape: "The Canis Minor constellation represents a small dog.",
    brightestStars: ["Procyon (α Canis Minoris)", "β Canis Minoris", "γ Canis Minoris"],
    interestingObjects: ["Gomeisa (β Canis Minoris)", "Open Cluster M41"],
    value: "cmi",
    info: "The Canis Minor constellation represents a small dog, often associated with the mythological dog Maera. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Canis Minor is best visible from Earth during the winter months in the Northern Hemisphere.",
    rightAscension: "07h 30m 00.00s",
    declination: "+10° 00′ 00.0″",
    area: "183.8 square degrees",
    imageSrc: "../images/canismajor.png"
  },
  {
    name: "Carina",
    shape: "The Carina constellation represents the keel of a ship. It is part of the larger constellation of Argo Navis.",
    brightestStars: ["Canopus (α Carinae)", "β Carinae", "η Carinae"],
    interestingObjects: ["Eta Carinae Nebula", "Carina Dwarf (Carina Dwarf Galaxy)"],
    value: "car",
    info: "The Carina constellation represents the keel of a ship, historically part of the larger constellation Argo Navis. It was introduced by the French astronomer Nicolas Louis de Lacaille in the 18th century. Carina is best visible from Earth during the summer months in the Southern Hemisphere.",
    rightAscension: "10h 00m 00.00s",
    declination: "-60° 00′ 00.0″",
    area: "494.2 square degrees",
    imageSrc: "../images/carina.png"
  },
  {
    name: "Cassiopeia",
    shape: "The Cassiopeia constellation represents a queen from Greek mythology, often depicted as sitting on a throne.",
    brightestStars: ["α Cassiopeiae (Schedar)", "β Cassiopeiae (Caph)", "γ Cassiopeiae (Navi)"],
    interestingObjects: ["Heart Nebula (IC 1805)", "Cassiopeia A (Supernova Remnant)"],
    value: "cas",
    info: "The Cassiopeia constellation represents the queen Cassiopeia from Greek mythology, often associated with the myth of Andromeda and Perseus. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Cassiopeia is best visible from Earth during the autumn and winter months in the Northern Hemisphere.",
    rightAscension: "01h 00m 00.00s",
    declination: "+60° 00′ 00.0″",
    area: "598.4 square degrees",
    imageSrc: "../images/cassiopeia.png"
  },
  {
    name: "Centaurus",
    shape: "The Centaurus constellation represents a centaur, a mythical creature with the upper body of a human and the lower body of a horse.",
    brightestStars: ["α Centauri", "β Centauri", "Proxima Centauri"],
    interestingObjects: ["Omega Centauri (NGC 5139)", "Centaurus A (NGC 5128)"],
    value: "cen",
    info: "The Centaurus constellation represents a centaur, a mythical creature from Greek mythology. It is one of the largest constellations and was introduced by the Greek astronomer Ptolemy in the 2nd century AD. Centaurus is best visible from Earth during the spring and summer months in the Southern Hemisphere.",
    rightAscension: "14h 30m 00.00s",
    declination: "-45° 00′ 00.0″",
    area: "1,060.4 square degrees",
    imageSrc: "../images/centaurus.png"
  },
  {
    name: "Cepheus",
    shape: "The Cepheus constellation represents a king from Greek mythology.",
    brightestStars: ["α Cephei (Alderamin)", "β Cephei", "γ Cephei"],
    interestingObjects: ["NGC 188 (Open Cluster)", "Cepheus B (Dark Nebula)"],
    value: "cep",
    info: "The Cepheus constellation represents a king from Greek mythology, often associated with the myth of Andromeda and Perseus. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Cepheus is best visible from Earth during the autumn and winter months in the Northern Hemisphere.",
    rightAscension: "22h 00m 00.00s",
    declination: "+70° 00′ 00.0″",
    area: "587.8 square degrees",
    imageSrc: "../images/cepheus.png"
  },
  {
    name: "Cetus",
    shape: "The Cetus constellation represents a sea monster from Greek mythology, often associated with the myth of Andromeda and Perseus.",
    brightestStars: ["α Ceti (Menkar)", "β Ceti (Deneb Kaitos)", "γ Ceti (Kaffaljidhma)"],
    interestingObjects: ["Mira (Omicron Ceti)", "Whale Galaxy (NGC 4631)"],
    value: "cet",
    info: "The Cetus constellation represents a sea monster from Greek mythology, often associated with the myth of Andromeda and Perseus. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Cetus is best visible from Earth during the autumn and winter months in the Northern Hemisphere.",
    rightAscension: "01h 30m 00.00s",
    declination: "-10° 00′ 00.0″",
    area: "1,231.4 square degrees",
    imageSrc: "../images/cetus.png"
  },
  {
    name: "Chamaeleon",
    shape: "The Chamaeleon constellation represents a chameleon, a lizard known for its ability to change colors.",
    brightestStars: ["α Chamaeleontis", "β Chamaeleontis", "γ Chamaeleontis"],
    interestingObjects: ["Eta Chamaeleontis (Double Star)", "Chamaeleon I (Dark Nebula)"],
    value: "cha",
    info: "The Chamaeleon constellation represents a chameleon, a lizard known for its ability to change colors. It was introduced by the Dutch navigators Pieter Dirkszoon Keyser and Frederick de Houtman in the late 16th century. Chamaeleon is best visible from Earth during the spring and summer months in the Southern Hemisphere.",
    rightAscension: "08h 00m 00.00s",
    declination: "-80° 00′ 00.0″",
    area: "132.5 square degrees",
    imageSrc: "../images/chamaeleon.png"
  },
  {
    name: "Cancer",
    shape: "The Cancer constellation represents a crab. It is one of the twelve constellations of the zodiac.",
    brightestStars: ["β Cancri", "α Cancri", "γ Cancri"],
    interestingObjects: ["Beehive Cluster (M44)", "Crab Nebula (M1)"],
    value: "cnc",
    info: "The Cancer constellation represents a crab and is one of the twelve constellations of the zodiac. It is best visible from Earth during the winter months in the Northern Hemisphere.",
    rightAscension: "08h 45m 00.00s",
    declination: "+20° 00′ 00.0″",
    area: "506.0 square degrees",
    imageSrc: "../images/cancer.png"
  },
  {
    name: "Canes Venatici",
    shape: "The Canes Venatici constellation represents two hunting dogs.",
    brightestStars: ["α Canum Venaticorum (Cor Caroli)", "β Canum Venaticorum", "δ Canum Venaticorum"],
    interestingObjects: ["Whirlpool Galaxy (M51)", "Canes Venatici I (Dwarf Galaxy)"],
    value: "cvn",
    info: "The Canes Venatici constellation represents two hunting dogs. It was introduced by the Polish astronomer Johannes Hevelius in the 17th century. Canes Venatici is best visible from Earth during the spring months in the Northern Hemisphere.",
    rightAscension: "13h 10m 00.00s",
    declination: "+40° 00′ 00.0″",
    area: "465.0 square degrees",
    imageSrc: "../images/canesvenatici.png"
  },
  {
    name: "Canis Major",
    shape: "The Canis Major constellation represents a great dog.",
    brightestStars: ["Sirius (α Canis Majoris)", "β Canis Majoris", "δ Canis Majoris"],
    interestingObjects: ["Great Orion Nebula (M42)", "Open Cluster NGC 2362"],
    value: "cma",
    info: "The Canis Major constellation represents a great dog, often associated with the mythological dog Laelaps or the dog of Orion. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Canis Major is best visible from Earth during the winter months in the Northern Hemisphere.",
    rightAscension: "06h 30m 00.00s",
    declination: "-20° 00′ 00.0″",
    area: "380.1 square degrees",
    imageSrc: "../images/canismajor.png"
  },
  {
    name: "Canis Minor",
    shape: "The Canis Minor constellation represents a small dog.",
    brightestStars: ["Procyon (α Canis Minoris)", "β Canis Minoris", "γ Canis Minoris"],
    interestingObjects: ["Gomeisa (β Canis Minoris)", "Open Cluster M41"],
    value: "cmi",
    info: "The Canis Minor constellation represents a small dog, often associated with the mythological dog Maera. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Canis Minor is best visible from Earth during the winter months in the Northern Hemisphere.",
    rightAscension: "07h 30m 00.00s",
    declination: "+10° 00′ 00.0″",
    area: "183.8 square degrees",
    imageSrc: "../images/canismajor.png"
  },
  {
    name: "Carina",
    shape: "The Carina constellation represents the keel of a ship. It is part of the larger constellation of Argo Navis.",
    brightestStars: ["Canopus (α Carinae)", "β Carinae", "η Carinae"],
    interestingObjects: ["Eta Carinae Nebula", "Carina Dwarf (Carina Dwarf Galaxy)"],
    value: "car",
    info: "The Carina constellation represents the keel of a ship, historically part of the larger constellation Argo Navis. It was introduced by the French astronomer Nicolas Louis de Lacaille in the 18th century. Carina is best visible from Earth during the summer months in the Southern Hemisphere.",
    rightAscension: "10h 00m 00.00s",
    declination: "-60° 00′ 00.0″",
    area: "494.2 square degrees",
    imageSrc: "../images/carina.png"
  },
  {
    name: "Cassiopeia",
    shape: "The Cassiopeia constellation represents a queen from Greek mythology, often depicted as sitting on a throne.",
    brightestStars: ["α Cassiopeiae (Schedar)", "β Cassiopeiae (Caph)", "γ Cassiopeiae (Navi)"],
    interestingObjects: ["Heart Nebula (IC 1805)", "Cassiopeia A (Supernova Remnant)"],
    value: "cas",
    info: "The Cassiopeia constellation represents the queen Cassiopeia from Greek mythology, often associated with the myth of Andromeda and Perseus. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Cassiopeia is best visible from Earth during the autumn and winter months in the Northern Hemisphere.",
    rightAscension: "01h 00m 00.00s",
    declination: "+60° 00′ 00.0″",
    area: "598.4 square degrees",
    imageSrc: "../images/cassiopeia.png"
  },
  {
    name: "Centaurus",
    shape: "The Centaurus constellation represents a centaur, a mythical creature with the upper body of a human and the lower body of a horse.",
    brightestStars: ["α Centauri", "β Centauri", "Proxima Centauri"],
    interestingObjects: ["Omega Centauri (NGC 5139)", "Centaurus A (NGC 5128)"],
    value: "cen",
    info: "The Centaurus constellation represents a centaur, a mythical creature from Greek mythology. It is one of the largest constellations and was introduced by the Greek astronomer Ptolemy in the 2nd century AD. Centaurus is best visible from Earth during the spring and summer months in the Southern Hemisphere.",
    rightAscension: "14h 30m 00.00s",
    declination: "-45° 00′ 00.0″",
    area: "1,060.4 square degrees",
    imageSrc: "../images/centaurus.png"
  },
  {
    name: "Cepheus",
    shape: "The Cepheus constellation represents a king from Greek mythology.",
    brightestStars: ["α Cephei (Alderamin)", "β Cephei", "γ Cephei"],
    interestingObjects: ["NGC 188 (Open Cluster)", "Cepheus B (Dark Nebula)"],
    value: "cep",
    info: "The Cepheus constellation represents a king from Greek mythology, often associated with the myth of Andromeda and Perseus. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Cepheus is best visible from Earth during the autumn and winter months in the Northern Hemisphere.",
    rightAscension: "22h 00m 00.00s",
    declination: "+70° 00′ 00.0″",
    area: "587.8 square degrees",
    imageSrc: "../images/cepheus.png"
  },
  {
    name: "Cetus",
    shape: "The Cetus constellation represents a sea monster from Greek mythology, often associated with the myth of Andromeda and Perseus.",
    brightestStars: ["α Ceti (Menkar)", "β Ceti (Deneb Kaitos)", "γ Ceti (Kaffaljidhma)"],
    interestingObjects: ["Mira (Omicron Ceti)", "Whale Galaxy (NGC 4631)"],
    value: "cet",
    info: "The Cetus constellation represents a sea monster from Greek mythology, often associated with the myth of Andromeda and Perseus. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Cetus is best visible from Earth during the autumn and winter months in the Northern Hemisphere.",
    rightAscension: "01h 30m 00.00s",
    declination: "-10° 00′ 00.0″",
    area: "1,231.4 square degrees",
    imageSrc: "../images/cetus.png"
  },
  {
    name: "Chamaeleon",
    shape: "The Chamaeleon constellation represents a chameleon, a lizard known for its ability to change colors.",
    brightestStars: ["α Chamaeleontis", "β Chamaeleontis", "γ Chamaeleontis"],
    interestingObjects: ["Eta Chamaeleontis (Double Star)", "Chamaeleon I (Dark Nebula)"],
    value: "cha",
    info: "The Chamaeleon constellation represents a chameleon, a lizard known for its ability to change colors. It was introduced by the Dutch navigators Pieter Dirkszoon Keyser and Frederick de Houtman in the late 16th century. Chamaeleon is best visible from Earth during the spring and summer months in the Southern Hemisphere.",
    rightAscension: "08h 00m 00.00s",
    declination: "-80° 00′ 00.0″",
    area: "132.5 square degrees",
    imageSrc: "../images/chamaeleon.png"
  },
  {
    name: "Delphinus",
    shape: "The Delphinus constellation represents a dolphin.",
    brightestStars: ["Sualocin (α Delphini)", "Rotanev (β Delphini)", "γ Delphini"],
    interestingObjects: ["NGC 7006 (Globular Cluster)", "Delphinus Dwarf (Delphinus Dwarf Galaxy)"],
    value: "del",
    info: "The Delphinus constellation represents a dolphin. It was introduced by the Greek astronomer Ptolemy in the 2nd century AD. Delphinus is best visible from Earth during the summer months in the Northern Hemisphere.",
    rightAscension: "20h 30m 00.00s",
    declination: "+15° 00′ 00.0″",
    area: "189.4 square degrees",
    imageSrc: "../images/delphinus.png"
  },
  {
    name: "Dorado",
    shape: "The Dorado constellation represents a dolphinfish or swordfish.",
    brightestStars: ["α Doradus (Acamar)", "β Doradus", "γ Doradus"],
    interestingObjects: ["Large Magellanic Cloud", "NGC 1566 (Barred Spiral Galaxy)"],
    value: "dor",
    info: "The Dorado constellation represents a dolphinfish or swordfish. It was introduced by the Dutch navigators Pieter Dirkszoon Keyser and Frederick de Houtman in the late 16th century. Dorado is best visible from Earth during the summer months in the Southern Hemisphere.",
    rightAscension: "05h 30m 00.00s",
    declination: "-60° 00′ 00.0″",
    area: "179.2 square degrees",
    imageSrc: "../images/dorado.png"
  },
  {
    name: "Draco",
    shape: "The Draco constellation represents a dragon.",
    brightestStars: ["γ Draconis (Eltanin)", "α Draconis (Thuban)", "η Draconis"],
    interestingObjects: ["Cat's Eye Nebula (NGC 6543)", "Draco Dwarf (Draco Dwarf Galaxy)"],
    value: "dra",
    info: "The Draco constellation represents a dragon. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Draco is best visible from Earth during the summer months in the Northern Hemisphere.",
    rightAscension: "17h 30m 00.00s",
    declination: "+60° 00′ 00.0″",
    area: "1,083.8 square degrees",
    imageSrc: "../images/draco.png"
  },
  {
    name: "Equuleus",
    shape: "The Equuleus constellation represents a small horse or foal.",
    brightestStars: ["α Equulei", "β Equulei", "γ Equulei"],
    interestingObjects: ["NGC 7015 (Spiral Galaxy)", "Barnard's Star (Red Dwarf)"],
    value: "equ",
    info: "The Equuleus constellation represents a small horse or foal. It was introduced by the Greek astronomer Ptolemy in the 2nd century AD. Equuleus is best visible from Earth during the summer months in the Northern Hemisphere.",
    rightAscension: "21h 00m 00.00s",
    declination: "+10° 00′ 00.0″",
    area: "71.4 square degrees",
    imageSrc: "../images/equuleus.png"
  },
  {
    name: "Eridanus",
    shape: "The Eridanus constellation represents a river.",
    brightestStars: ["Achernar (α Eridani)", "Cursa (β Eridani)", "Zaurak (γ Eridani)"],
    interestingObjects: ["Eridanus Cluster (Galaxy Cluster)", "NGC 1535 (Planetary Nebula)"],
    value: "eri",
    info: "The Eridanus constellation represents a river, often associated with the mythological river-god. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Eridanus is best visible from Earth during the winter months in the Southern Hemisphere.",
    rightAscension: "04h 00m 00.00s",
    declination: "-20° 00′ 00.0″",
    area: "1,138.3 square degrees",
    imageSrc: "../images/eridanus.png"
  },
  {
    name: "Fornax",
    shape: "The Fornax constellation represents a furnace.",
    brightestStars: ["α Fornacis", "β Fornacis", "δ Fornacis"],
    interestingObjects: ["NGC 1316 (Fornax A)", "Fornax Dwarf (Fornax Dwarf Galaxy)"],
    value: "for",
    info: "The Fornax constellation represents a furnace. It was introduced by the French astronomer Nicolas Louis de Lacaille in the 18th century. Fornax is best visible from Earth during the autumn and winter months in the Southern Hemisphere.",
    rightAscension: "02h 00m 00.00s",
    declination: "-30° 00′ 00.0″",
    area: "397.5 square degrees",
    imageSrc: "../images/fornax.png"
  },
  {
    name: "Gemini",
    shape: "The Gemini constellation represents the twins Castor and Pollux from Greek mythology.",
    brightestStars: ["Castor (α Geminorum)", "Pollux (β Geminorum)", "Alhena (γ Geminorum)"],
    interestingObjects: ["Eskimo Nebula (NGC 2392)", "Messier 35 (Open Cluster)"],
    value: "gem",
    info: "The Gemini constellation represents the twins Castor and Pollux from Greek mythology. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Gemini is best visible from Earth during the winter and spring months in the Northern Hemisphere.",
    rightAscension: "07h 00m 00.00s",
    declination: "+20° 00′ 00.0″",
    area: "514.0 square degrees",
    imageSrc: "../images/gemini.png"
  },
  {
    name: "Grus",
    shape: "The Grus constellation represents a crane or bird.",
    brightestStars: ["α Gruis (Alnair)", "β Gruis", "γ Gruis"],
    interestingObjects: ["Small Magellanic Cloud", "NGC 7424 (Barred Spiral Galaxy)"],
    value: "gru",
    info: "The Grus constellation represents a crane or bird. It was introduced by the Dutch navigators Pieter Dirkszoon Keyser and Frederick de Houtman in the late 16th century. Grus is best visible from Earth during the summer months in the Southern Hemisphere.",
    rightAscension: "22h 00m 00.00s",
    declination: "-45° 00′ 00.0″",
    area: "366.7 square degrees",
    imageSrc: "../images/grus.png"
  },
  {
    name: "Hercules",
    shape: "The Hercules constellation represents the mythical hero Hercules.",
    brightestStars: ["Rasalgethi (α Herculis)", "Kornephoros (β Herculis)", "Rasalhague (α Ophiuchi)"],
    interestingObjects: ["Great Globular Cluster (M13)", "Hercules A (Radio Galaxy)"],
    value: "her",
    info: "The Hercules constellation represents the mythical hero Hercules. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Hercules is best visible from Earth during the summer months in the Northern Hemisphere.",
    rightAscension: "17h 00m 00.00s",
    declination: "+30° 00′ 00.0″",
    area: "1225.1 square degrees",
    imageSrc: "../images/hercules.png"
  },
  {
    name: "Horologium",
    shape: "The Horologium constellation represents a clock or pendulum clock.",
    brightestStars: ["α Horologii", "β Horologii", "γ Horologii"],
    interestingObjects: ["NGC 1261 (Globular Cluster)", "Horologium Supercluster (Galaxy Supercluster)"],
    value: "hor",
    info: "The Horologium constellation represents a clock or pendulum clock. It was introduced by the French astronomer Nicolas Louis de Lacaille in the 18th century. Horologium is best visible from Earth during the winter months in the Southern Hemisphere.",
    rightAscension: "03h 30m 00.00s",
    declination: "-50° 00′ 00.0″",
    area: "249.9 square degrees",
    imageSrc: "../images/horologium.png"
  },
  {
    name: "Hydra",
    shape: "The Hydra constellation represents a water snake or serpent.",
    brightestStars: ["Alphard (α Hydrae)", "γ Hydrae", "δ Hydrae"],
    interestingObjects: ["Messier 83 (Southern Pinwheel Galaxy)", "Hydra A (Radio Galaxy)"],
    value: "hya",
    info: "The Hydra constellation represents a water snake or serpent. It is the largest of the 88 modern constellations. Hydra is best visible from Earth during the spring months in the Northern Hemisphere.",
    rightAscension: "10h 00m 00.00s",
    declination: "-20° 00′ 00.0″",
    area: "1302.8 square degrees",
    imageSrc: "../images/hydra.png"
  },
  {
    name: "Hydrus",
    shape: "The Hydrus constellation represents a male water snake or serpent.",
    brightestStars: ["α Hydri", "β Hydri", "γ Hydri"],
    interestingObjects: ["Tucana Dwarf (Tucana Dwarf Galaxy)", "NGC 602 (Open Cluster)"],
    value: "hyi",
    info: "The Hydrus constellation represents a male water snake or serpent. It was introduced by the Dutch navigators Pieter Dirkszoon Keyser and Frederick de Houtman in the late 16th century. Hydrus is best visible from Earth during the summer months in the Southern Hemisphere.",
    rightAscension: "02h 00m 00.00s",
    declination: "-70° 00′ 00.0″",
    area: "243.4 square degrees",
    imageSrc: "../images/hydrus.png"
  },
  {
    name: "Indus",
    shape: "The Indus constellation represents an Indian.",
    brightestStars: ["α Indi", "β Indi", "γ Indi"],
    interestingObjects: ["Indus Cluster (Galaxy Cluster)", "Indus Dwarf (Indus Dwarf Galaxy)"],
    value: "ind",
    info: "The Indus constellation represents an Indian. It was introduced by the Dutch navigators Pieter Dirkszoon Keyser and Frederick de Houtman in the late 16th century. Indus is best visible from Earth during the winter months in the Southern Hemisphere.",
    rightAscension: "21h 00m 00.00s",
    declination: "-60° 00′ 00.0″",
    area: "294.0 square degrees",
    imageSrc: "../images/indus.png"
  },
  {
    name: "Lacerta",
    shape: "The Lacerta constellation represents a lizard.",
    brightestStars: ["α Lacertae", "β Lacertae", "γ Lacertae"],
    interestingObjects: ["Messier 52 (Open Cluster)", "Lacerta Dwarf (Lacerta Dwarf Galaxy)"],
    value: "lac",
    info: "The Lacerta constellation represents a lizard. It was introduced by the Polish astronomer Johannes Hevelius in the 17th century. Lacerta is best visible from Earth during the autumn months in the Northern Hemisphere.",
    rightAscension: "22h 30m 00.00s",
    declination: "+45° 00′ 00.0″",
    area: "201.0 square degrees",
    imageSrc: "../images/lacerta.png"
  },
  {
    name: "Leo",
    shape: "The Leo constellation represents a lion.",
    brightestStars: ["Regulus (α Leonis)", "Denebola (β Leonis)", "Algieba (γ Leonis)"],
    interestingObjects: ["Leo Triplet (Galaxy Group)", "NGC 3628 (Hamburger Galaxy)"],
    value: "leo",
    info: "The Leo constellation represents a lion. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Leo is best visible from Earth during the spring months in the Northern Hemisphere.",
    rightAscension: "11h 00m 00.00s",
    declination: "+15° 00′ 00.0″",
    area: "946.0 square degrees",
    imageSrc: "../images/leo.png"
  },
  {
    name: "Leo Minor",
    shape: "The Leo Minor constellation represents a small lion.",
    brightestStars: ["46 Leonis Minoris", "21 Leonis Minoris", "β Leonis Minoris"],
    interestingObjects: ["NGC 3003 (Spiral Galaxy)", "Leonis Minoris Dwarf (Leo Minor Dwarf Galaxy)"],
    value: "lmi",
    info: "The Leo Minor constellation represents a small lion. It was introduced by the Dutch astronomer Petrus Plancius in the late 16th century. Leo Minor is best visible from Earth during the spring months in the Northern Hemisphere.",
    rightAscension: "10h 30m 00.00s",
    declination: "+35° 00′ 00.0″",
    area: "232.0 square degrees",
    imageSrc: "../images/leo-minor.png"
  },
  {
    name: "Lepus",
    shape: "The Lepus constellation represents a hare or rabbit.",
    brightestStars: ["Arneb (α Leporis)", "Nihal (β Leporis)", "γ Leporis"],
    interestingObjects: ["Messier 79 (Globular Cluster)", "Lepus Dwarf (Lepus Dwarf Galaxy)"],
    value: "lep",
    info: "The Lepus constellation represents a hare or rabbit. It was introduced by the Greek astronomer Ptolemy in the 2nd century AD. Lepus is best visible from Earth during the winter months in the Southern Hemisphere.",
    rightAscension: "05h 30m 00.00s",
    declination: "-20° 00′ 00.0″",
    area: "290.3 square degrees",
    imageSrc: "../images/lepus.png"
  },
  {
    name: "Libra",
    shape: "The Libra constellation represents scales or a balance.",
    brightestStars: ["Zubenelgenubi (α Librae)", "Zubeneschamali (β Librae)", "γ Librae"],
    interestingObjects: ["NGC 5897 (Globular Cluster)", "Zubenelakrab (ζ Librae)"],
    value: "lib",
    info: "The Libra constellation represents scales or a balance. It was introduced by the Greek astronomer Ptolemy in the 2nd century AD. Libra is best visible from Earth during the spring months in the Northern Hemisphere.",
    rightAscension: "15h 00m 00.00s",
    declination: "-15° 00′ 00.0″",
    area: "538.1 square degrees",
    imageSrc: "../images/libra.png"
  },
  {
    name: "Lupus",
    shape: "The Lupus constellation represents a wolf.",
    brightestStars: ["α Lupi (Men)", "β Lupi (Ke Kouan)", "γ Lupi"],
    interestingObjects: ["Lupus 3 (Dark Nebula)", "Lupus I (Galaxy Cluster)"],
    value: "lup",
    info: "The Lupus constellation represents a wolf. It was introduced by the Greek astronomer Ptolemy in the 2nd century AD. Lupus is best visible from Earth during the winter and spring months in the Southern Hemisphere.",
    rightAscension: "15h 30m 00.00s",
    declination: "-40° 00′ 00.0″",
    area: "333.7 square degrees",
    imageSrc: "../images/lupus.png"
  },
  {
    name: "Lynx",
    shape: "The Lynx constellation represents a lynx, a wild cat.",
    brightestStars: ["α Lyncis", "38 Lyncis", "21 Lyncis"],
    interestingObjects: ["Messier 105 (Elliptical Galaxy)", "Lynx Arc (Galaxy Supercluster)"],
    value: "lyn",
    info: "The Lynx constellation represents a lynx, a wild cat. It was introduced by the Polish astronomer Johannes Hevelius in the 17th century. Lynx is best visible from Earth during the winter and spring months in the Northern Hemisphere.",
    rightAscension: "07h 30m 00.00s",
    declination: "+50° 00′ 00.0″",
    area: "545.4 square degrees",
    imageSrc: "../images/lynx.png"
  },
  {
    name: "Lyra",
    shape: "The Lyra constellation represents a lyre or small harp.",
    brightestStars: ["Vega (α Lyrae)", "β Lyrae (Sheliak)", "γ Lyrae (Sulafat)"],
    interestingObjects: ["Ring Nebula (Messier 57)", "Vega's Gaps (Debris Disk)"],
    value: "lyr",
    info: "The Lyra constellation represents a lyre or small harp. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Lyra is best visible from Earth during the summer months in the Northern Hemisphere.",
    rightAscension: "18h 30m 00.00s",
    declination: "+40° 00′ 00.0″",
    area: "286.5 square degrees",
    imageSrc: "../images/lyra.png"
  },
  {
    name: "Mensa",
    shape: "The Mensa constellation represents a table.",
    brightestStars: ["α Mensae", "β Mensae", "γ Mensae"],
    interestingObjects: ["IC 2554 (Spindle Galaxy)", "Menzel 3 (Planetary Nebula)"],
    value: "men",
    info: "The Mensa constellation represents a table. It was introduced by the French astronomer Nicolas Louis de Lacaille in the 18th century. Mensa is best visible from Earth during the winter months in the Southern Hemisphere.",
    rightAscension: "06h 00m 00.00s",
    declination: "-75° 00′ 00.0″",
    area: "153.5 square degrees",
    imageSrc: "../images/mensa.png"
  },
  {
    name: "Microscopium",
    shape: "The Microscopium constellation represents a microscope.",
    brightestStars: ["γ Microscopii", "β Microscopii", "δ Microscopii"],
    interestingObjects: ["NGC 6925 (Barred Spiral Galaxy)", "R Microscopii (Mira Variable Star)"],
    value: "mic",
    info: "The Microscopium constellation represents a microscope. It was introduced by the French astronomer Nicolas Louis de Lacaille in the 18th century. Microscopium is best visible from Earth during the summer months in the Southern Hemisphere.",
    rightAscension: "21h 00m 00.00s",
    declination: "-35° 00′ 00.0″",
    area: "210.3 square degrees",
    imageSrc: "../images/microscopium.png"
  },
  {
    name: "Monoceros",
    shape: "The Monoceros constellation represents a unicorn.",
    brightestStars: ["β Monocerotis", "α Monocerotis", "γ Monocerotis"],
    interestingObjects: ["Rosette Nebula (NGC 2237)", "NGC 2264 (Christmas Tree Cluster)"],
    value: "mon",
    info: "The Monoceros constellation represents a unicorn. It was introduced by the Dutch navigators Pieter Dirkszoon Keyser and Frederick de Houtman in the late 16th century. Monoceros is best visible from Earth during the winter months in the Northern Hemisphere.",
    rightAscension: "07h 30m 00.00s",
    declination: "-05° 00′ 00.0″",
    area: "482.8 square degrees",
    imageSrc: "../images/monoceros.png"
  },
  {
    name: "Musca",
    shape: "The Musca constellation represents a fly.",
    brightestStars: ["α Muscae", "β Muscae", "γ Muscae"],
    interestingObjects: ["NGC 4372 (Globular Cluster)", "Musca Australis (Southern Fly)"],
    value: "mus",
    info: "The Musca constellation represents a fly. It was introduced by the Dutch navigators Pieter Dirkszoon Keyser and Frederick de Houtman in the late 16th century. Musca is best visible from Earth during the summer months in the Southern Hemisphere.",
    rightAscension: "12h 30m 00.00s",
    declination: "-70° 00′ 00.0″",
    area: "138.3 square degrees",
    imageSrc: "../images/musca.png"
  },
  {
    name: "Norma",
    shape: "The Norma constellation represents a set square.",
    brightestStars: ["γ Normae", "β Normae", "δ Normae"],
    interestingObjects: ["NGC 6087 (Open Cluster)", "Norma Cluster (Galaxy Cluster)"],
    value: "nor",
    info: "The Norma constellation represents a set square. It was introduced by the French astronomer Nicolas Louis de Lacaille in the 18th century. Norma is best visible from Earth during the summer months in the Southern Hemisphere.",
    rightAscension: "16h 00m 00.00s",
    declination: "-50° 00′ 00.0″",
    area: "165.3 square degrees",
    imageSrc: "../images/norma.png"
  },
  {
    name: "Octans",
    shape: "The Octans constellation represents an octant, a navigational instrument.",
    brightestStars: ["α Octantis", "β Octantis", "γ Octantis"],
    interestingObjects: ["NGC 7099 (Globular Cluster)", "Octans Dwarf (Octans Dwarf Galaxy)"],
    value: "oct",
    info: "The Octans constellation represents an octant, a navigational instrument. It was introduced by the French astronomer Nicolas Louis de Lacaille in the 18th century. Octans is best visible from Earth during the spring months in the Southern Hemisphere.",
    rightAscension: "21h 30m 00.00s",
    declination: "-90° 00′ 00.0″",
    area: "291.4 square degrees",
    imageSrc: "../images/octans.png"
  },
  {
    name: "Ophiuchus",
    shape: "The Ophiuchus constellation represents a serpent-bearer.",
    brightestStars: ["Rasalhague (α Ophiuchi)", "Sabik (η Ophiuchi)", "Cebalrai (β Ophiuchi)"],
    interestingObjects: ["Barnard's Star (Red Dwarf)", "Ophiuchus Cluster (Galaxy Cluster)"],
    value: "oph",
    info: "The Ophiuchus constellation represents a serpent-bearer. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Ophiuchus is best visible from Earth during the summer months in the Northern Hemisphere.",
    rightAscension: "17h 00m 00.00s",
    declination: "+00° 00′ 00.0″",
    area: "948.0 square degrees",
    imageSrc: "../images/ophiuchus.png"
  },
  {
    name: "Orion",
    shape: "The Orion constellation represents a hunter.",
    brightestStars: ["Rigel (β Orionis)", "Betelgeuse (α Orionis)", "Bellatrix (γ Orionis)"],
    interestingObjects: ["Orion Nebula (Messier 42)", "Horsehead Nebula (IC 434)"],
    value: "ori",
    info: "The Orion constellation represents a hunter. It is one of the most recognizable constellations in the night sky. Orion is best visible from Earth during the winter months in both the Northern and Southern Hemispheres.",
    rightAscension: "05h 00m 00.00s",
    declination: "+00° 00′ 00.0″",
    area: "594.1 square degrees",
    imageSrc: "../images/orion.png"
  },
  {
    name: "Pavo",
    shape: "The Pavo constellation represents a peacock.",
    brightestStars: ["Peacock (α Pavonis)", "β Pavonis", "γ Pavonis"],
    interestingObjects: ["Pavo Galaxy Cluster (Galaxy Cluster)", "NGC 6752 (Globular Cluster)"],
    value: "pav",
    info: "The Pavo constellation represents a peacock. It was introduced by the Dutch navigators Pieter Dirkszoon Keyser and Frederick de Houtman in the late 16th century. Pavo is best visible from Earth during the summer months in the Southern Hemisphere.",
    rightAscension: "19h 00m 00.00s",
    declination: "-65° 00′ 00.0″",
    area: "377.4 square degrees",
    imageSrc: "../images/pavo.png"
  },
  {
    name: "Pegasus",
    shape: "The Pegasus constellation represents a winged horse.",
    brightestStars: ["Enif (ε Pegasi)", "Scheat (β Pegasi)", "Markab (α Pegasi)"],
    interestingObjects: ["Andromeda Galaxy (Messier 31)", "Pegasus Dwarf Irregular (Pegasus Dwarf Galaxy)"],
    value: "peg",
    info: "The Pegasus constellation represents a winged horse. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Pegasus is best visible from Earth during the autumn months in the Northern Hemisphere.",
    rightAscension: "22h 00m 00.00s",
    declination: "+20° 00′ 00.0″",
    area: "1121.7 square degrees",
    imageSrc: "../images/pegasus.png"
  },
  {
    name: "Perseus",
    shape: "The Perseus constellation represents a hero from Greek mythology.",
    brightestStars: ["Mirfak (α Persei)", "Algol (β Persei)", "Menkib (ξ Persei)"],
    interestingObjects: ["Double Cluster (NGC 869 and NGC 884)", "California Nebula (NGC 1499)"],
    value: "per",
    info: "The Perseus constellation represents a hero from Greek mythology. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Perseus is best visible from Earth during the winter months in the Northern Hemisphere.",
    rightAscension: "04h 00m 00.00s",
    declination: "+45° 00′ 00.0″",
    area: "615.2 square degrees",
    imageSrc: "../images/perseus.png"
  },
  {
    name: "Phoenix",
    shape: "The Phoenix constellation represents a phoenix, a mythological bird.",
    brightestStars: ["Ankaa (α Phoenicis)", "β Phoenicis", "γ Phoenicis"],
    interestingObjects: ["Phoenix Dwarf (Phoenix Dwarf Galaxy)", "NGC 625 (Open Cluster)"],
    value: "pho",
    info: "The Phoenix constellation represents a phoenix, a mythological bird. It was introduced by the Dutch navigators Pieter Dirkszoon Keyser and Frederick de Houtman in the late 16th century. Phoenix is best visible from Earth during the summer months in the Southern Hemisphere.",
    rightAscension: "02h 30m 00.00s",
    declination: "-55° 00′ 00.0″",
    area: "469.2 square degrees",
    imageSrc: "../images/phoenix.png"
  },
  {
    name: "Pictor",
    shape: "The Pictor constellation represents an easel.",
    brightestStars: ["α Pictoris", "β Pictoris", "γ Pictoris"],
    interestingObjects: ["Pictor A (Radio Galaxy)", "Dorado Group (Galaxy Group)"],
    value: "pic",
    info: "The Pictor constellation represents an easel. It was introduced by the French astronomer Nicolas Louis de Lacaille in the 18th century. Pictor is best visible from Earth during the summer months in the Southern Hemisphere.",
    rightAscension: "05h 30m 00.00s",
    declination: "-50° 00′ 00.0″",
    area: "246.8 square degrees",
    imageSrc: "../images/pictor.png"
  },
  {
    name: "Pisces",
    shape: "The Pisces constellation represents two fish.",
    brightestStars: ["Alrisha (α Piscium)", "Fum al Samakah (β Piscium)", "Kullat Nunu (η Piscium)"],
    interestingObjects: ["Pisces Cluster (Galaxy Cluster)", "Messier 74 (Spiral Galaxy)"],
    value: "psc",
    info: "The Pisces constellation represents two fish. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Pisces is best visible from Earth during the autumn and winter months in the Northern Hemisphere.",
    rightAscension: "01h 30m 00.00s",
    declination: "+15° 00′ 00.0″",
    area: "889.4 square degrees",
    imageSrc: "../images/pisces.png"
  },
  {
    name: "Piscis Austrinus",
    shape: "The Piscis Austrinus constellation represents a southern fish.",
    brightestStars: ["Fomalhaut (α Piscis Austrini)", "ε Piscis Austrini", "γ Piscis Austrini"],
    interestingObjects: ["Piscis Austrinus Cluster (Galaxy Cluster)", "Fomalhaut b (Exoplanet)"],
    value: "psa",
    info: "The Piscis Austrinus constellation represents a southern fish. It was introduced by the Greek astronomer Ptolemy in the 2nd century AD. Piscis Austrinus is best visible from Earth during the autumn months in the Northern Hemisphere.",
    rightAscension: "22h 30m 00.00s",
    declination: "-30° 00′ 00.0″",
    area: "245.4 square degrees",
    imageSrc: "../images/piscis-austrinus.png"
  },
  {
    name: "Puppis",
    shape: "The Puppis constellation represents the poop deck of a ship.",
    brightestStars: ["Naos (ζ Puppis)", "Asmidiske (κ Puppis)", "Phact (α Puppis)"],
    interestingObjects: ["Eta Carinae Nebula", "Messier 46 (Open Cluster)"],
    value: "pup",
    info: "The Puppis constellation represents the poop deck of a ship. It is one of the three constellations that form the ancient constellation Argo Navis. Puppis is best visible from Earth during the winter and spring months in the Southern Hemisphere.",
    rightAscension: "07h 00m 00.00s",
    declination: "-30° 00′ 00.0″",
    area: "673.4 square degrees",
    imageSrc: "../images/puppis.png"
  },
  {
    name: "Pyxis",
    shape: "The Pyxis constellation represents a mariner's compass.",
    brightestStars: ["α Pyxidis", "β Pyxidis", "γ Pyxidis"],
    interestingObjects: ["Galactic South Pole (Celestial Coordinate System)", "RS Pyxidis (Nova)"],
    value: "pyx",
    info: "The Pyxis constellation represents a mariner's compass. It was introduced by the French astronomer Nicolas Louis de Lacaille in the 18th century. Pyxis is best visible from Earth during the spring and summer months in the Southern Hemisphere.",
    rightAscension: "09h 00m 00.00s",
    declination: "-30° 00′ 00.0″",
    area: "221.0 square degrees",
    imageSrc: "../images/pyxis.png"
  },
  {
    name: "Reticulum",
    shape: "The Reticulum constellation represents a reticle, a grid used in telescopes.",
    brightestStars: ["α Reticuli", "β Reticuli", "γ Reticuli"],
    interestingObjects: ["Reticulum II (Dwarf Galaxy)", "Reticulum III (Dwarf Galaxy)"],
    value: "ret",
    info: "The Reticulum constellation represents a reticle, a grid used in telescopes. It was introduced by the French astronomer Nicolas Louis de Lacaille in the 18th century. Reticulum is best visible from Earth during the summer and autumn months in the Southern Hemisphere.",
    rightAscension: "03h 00m 00.00s",
    declination: "-60° 00′ 00.0″",
    area: "114.4 square degrees",
    imageSrc: "../images/reticulum.png"
  },
  {
    name: "Sagitta",
    shape: "The Sagitta constellation represents an arrow.",
    brightestStars: ["γ Sagittae", "δ Sagittae", "β Sagittae"],
    interestingObjects: ["Messier 71 (Globular Cluster)", "Sagitta Dwarf (Sagittae Dwarf Galaxy)"],
    value: "sge",
    info: "The Sagitta constellation represents an arrow. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Sagitta is best visible from Earth during the summer months in the Northern Hemisphere.",
    rightAscension: "19h 00m 00.00s",
    declination: "+20° 00′ 00.0″",
    area: "80.0 square degrees",
    imageSrc: "../images/sagitta.png"
  },
  {
    name: "Sagittarius",
    shape: "The Sagittarius constellation represents a centaur archer.",
    brightestStars: ["Kaus Australis (ε Sagittarii)", "Nunki (σ Sagittarii)", "Ascella (ζ Sagittarii)"],
    interestingObjects: ["Milky Way Galaxy", "Lagoon Nebula (Messier 8)"],
    value: "sgr",
    info: "The Sagittarius constellation represents a centaur archer. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Sagittarius is best visible from Earth during the summer months in the Southern Hemisphere.",
    rightAscension: "18h 00m 00.00s",
    declination: "-25° 00′ 00.0″",
    area: "867.4 square degrees",
    imageSrc: "../images/sagittarius.png"
  },
  {
    name: "Sculptor",
    shape: "The Sculptor constellation represents a sculptor's tool.",
    brightestStars: ["α Sculptoris", "β Sculptoris", "γ Sculptoris"],
    interestingObjects: ["Sculptor Dwarf (Sculptor Dwarf Galaxy)", "NGC 253 (Sculptor Galaxy)"],
    value: "scl",
    info: "The Sculptor constellation represents a sculptor's tool. It was introduced by the French astronomer Nicolas Louis de Lacaille in the 18th century. Sculptor is best visible from Earth during the autumn months in the Southern Hemisphere.",
    rightAscension: "00h 30m 00.00s",
    declination: "-30° 00′ 00.0″",
    area: "474.8 square degrees",
    imageSrc: "../images/sculptor.png"
  },
  {
    name: "Scutum",
    shape: "The Scutum constellation represents a shield.",
    brightestStars: ["α Scuti", "β Scuti", "δ Scuti"],
    interestingObjects: ["Wild Duck Cluster (Messier 11)", "Scutum Dwarf (Scutum Dwarf Galaxy)"],
    value: "sct",
    info: "The Scutum constellation represents a shield. It was introduced by the Polish astronomer Johannes Hevelius in the 17th century. Scutum is best visible from Earth during the summer months in the Northern Hemisphere.",
    rightAscension: "18h 00m 00.00s",
    declination: "-10° 00′ 00.0″",
    area: "109.0 square degrees",
    imageSrc: "../images/scutum.png"
  },
  {
    name: "Serpens Caput",
    shape: "The Serpens Caput constellation represents the head of a serpent.",
    brightestStars: ["Unukalhai (α Serpentis)", "β Serpentis", "γ Serpentis"],
    interestingObjects: ["Eagle Nebula (Messier 16)", "Serpens Caput Galaxy Cluster"],
    value: "ser",
    info: "The Serpens Caput constellation represents the head of a serpent. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Serpens Caput is best visible from Earth during the summer months in the Northern Hemisphere.",
    rightAscension: "15h 30m 00.00s",
    declination: "+10° 00′ 00.0″",
    area: "636.0 square degrees",
    imageSrc: "../images/serpens-caput.png"
  },
  {
    name: "Serpens Cauda",
    shape: "The Serpens Cauda constellation represents the tail of a serpent.",
    brightestStars: ["η Serpentis", "δ Serpentis", "β Serpentis"],
    interestingObjects: ["Eagle Nebula (Messier 16)", "Serpens Cauda Galaxy Cluster"],
    value: "ser",
    info: "The Serpens Cauda constellation represents the tail of a serpent. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Serpens Cauda is best visible from Earth during the summer months in the Northern Hemisphere.",
    rightAscension: "18h 00m 00.00s",
    declination: "-10° 00′ 00.0″",
    area: "637.0 square degrees",
    imageSrc: "../images/serpens-cauda.png"
  },
  {
    name: "Sextans",
    shape: "The Sextans constellation represents a sextant, a navigational instrument.",
    brightestStars: ["α Sextantis", "β Sextantis", "γ Sextantis"],
    interestingObjects: ["Sextans A (Dwarf Galaxy)", "NGC 3115 (Spindle Galaxy)"],
    value: "sex",
    info: "The Sextans constellation represents a sextant, a navigational instrument. It was introduced by the Polish astronomer Johannes Hevelius in the 17th century. Sextans is best visible from Earth during the spring months in the Northern Hemisphere.",
    rightAscension: "10h 00m 00.00s",
    declination: "-00° 00′ 00.0″",
    area: "313.0 square degrees",
    imageSrc: "../images/sextans.png"
  },
  {
    name: "Taurus",
    shape: "The Taurus constellation represents a bull.",
    brightestStars: ["Aldebaran (α Tauri)", "Elnath (β Tauri)", "Alcyone (η Tauri)"],
    interestingObjects: ["Pleiades (Seven Sisters, Messier 45)", "Crab Nebula (Messier 1)"],
    value: "tau",
    info: "The Taurus constellation represents a bull. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Taurus is best visible from Earth during the winter months in the Northern Hemisphere.",
    rightAscension: "04h 30m 00.00s",
    declination: "+15° 00′ 00.0″",
    area: "797.0 square degrees",
    imageSrc: "../images/taurus.png"
  },
  {
    name: "Telescopium",
    shape: "The Telescopium constellation represents a telescope.",
    brightestStars: ["α Telescopii", "β Telescopii", "γ Telescopii"],
    interestingObjects: ["NGC 6863 (Planetary Nebula)", "Telescopium Cluster (Galaxy Cluster)"],
    value: "tel",
    info: "The Telescopium constellation represents a telescope. It was introduced by the French astronomer Nicolas Louis de Lacaille in the 18th century. Telescopium is best visible from Earth during the winter and spring months in the Southern Hemisphere.",
    rightAscension: "18h 30m 00.00s",
    declination: "-50° 00′ 00.0″",
    area: "252.0 square degrees",
    imageSrc: "../images/telescopium.png"
  },
  {
    name: "Triangulum",
    shape: "The Triangulum constellation represents a triangle.",
    brightestStars: ["β Trianguli", "γ Trianguli", "δ Trianguli"],
    interestingObjects: ["Triangulum Galaxy (Messier 33)", "NGC 672 (Barred Spiral Galaxy)"],
    value: "tri",
    info: "The Triangulum constellation represents a triangle. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Triangulum is best visible from Earth during the autumn months in the Northern Hemisphere.",
    rightAscension: "02h 00m 00.00s",
    declination: "+30° 00′ 00.0″",
    area: "131.0 square degrees",
    imageSrc: "../images/triangulum.png"
  },
  {
    name: "Triangulum Australe",
    shape: "The Triangulum Australe constellation represents a southern triangle.",
    brightestStars: ["Atria (α Trianguli Australis)", "β Trianguli Australis", "γ Trianguli Australis"],
    interestingObjects: ["Triangulum Australe Galaxy Cluster", "NGC 6025 (Open Cluster)"],
    value: "tra",
    info: "The Triangulum Australe constellation represents a southern triangle. It was introduced by the Dutch navigators Pieter Dirkszoon Keyser and Frederick de Houtman in the late 16th century. Triangulum Australe is best visible from Earth during the summer months in the Southern Hemisphere.",
    rightAscension: "15h 00m 00.00s",
    declination: "-65° 00′ 00.0″",
    area: "110.0 square degrees",
    imageSrc: "../images/triangulum-australe.png"
  },
  {
    name: "Tucana",
    shape: "The Tucana constellation represents a toucan, a bird species.",
    brightestStars: ["α Tucanae", "β Tucanae", "γ Tucanae"],
    interestingObjects: ["Small Magellanic Cloud (Dwarf Galaxy)", "47 Tucanae (Globular Cluster)"],
    value: "tuc",
    info: "The Tucana constellation represents a toucan, a bird species. It was introduced by the Dutch navigators Pieter Dirkszoon Keyser and Frederick de Houtman in the late 16th century. Tucana is best visible from Earth during the spring months in the Southern Hemisphere.",
    rightAscension: "23h 30m 00.00s",
    declination: "-65° 00′ 00.0″",
    area: "294.4 square degrees",
    imageSrc: "../images/tucana.png"
  },
  {
    name: "Ursa Major",
    shape: "The Ursa Major constellation represents a great bear.",
    brightestStars: ["Dubhe (α Ursae Majoris)", "Merak (β Ursae Majoris)", "Alioth (ε Ursae Majoris)"],
    interestingObjects: ["Whirlpool Galaxy (Messier 51)", "Owl Nebula (Messier 97)"],
    value: "uma",
    info: "The Ursa Major constellation represents a great bear. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Ursa Major is best visible from Earth during the spring months in the Northern Hemisphere.",
    rightAscension: "10h 00m 00.00s",
    declination: "+50° 00′ 00.0″",
    area: "1279.7 square degrees",
    imageSrc: "../images/ursa-major.png"
  },
  {
    name: "Ursa Minor",
    shape: "The Ursa Minor constellation represents a little bear.",
    brightestStars: ["Polaris (α Ursae Minoris)", "Kochab (β Ursae Minoris)", "Pherkad (γ Ursae Minoris)"],
    interestingObjects: ["Little Dumbbell Nebula (Messier 76)", "Ursa Minor Dwarf (Ursa Minor Dwarf Galaxy)"],
    value: "umi",
    info: "The Ursa Minor constellation represents a little bear. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Ursa Minor is best visible from Earth during the spring months in the Northern Hemisphere.",
    rightAscension: "15h 00m 00.00s",
    declination: "+75° 00′ 00.0″",
    area: "255.9 square degrees",
    imageSrc: "../images/ursa-minor.png"
  },
  {
    name: "Vela",
    shape: "The Vela constellation represents the sails of a ship.",
    brightestStars: ["γ Velorum", "κ Velorum", "α Velorum"],
    interestingObjects: ["Vela Supernova Remnant", "Eta Carinae Nebula"],
    value: "vel",
    info: "The Vela constellation represents the sails of a ship. It is one of the three constellations that form the ancient constellation Argo Navis. Vela is best visible from Earth during the summer months in the Southern Hemisphere.",
    rightAscension: "09h 00m 00.00s",
    declination: "-50° 00′ 00.0″",
    area: "500.5 square degrees",
    imageSrc: "../images/vela.png"
  },
  {
    name: "Virgo",
    shape: "The Virgo constellation represents a maiden.",
    brightestStars: ["Spica (α Virginis)", "Porrima (γ Virginis)", "Vindemiatrix (ε Virginis)"],
    interestingObjects: ["Sombrero Galaxy (Messier 104)", "Virgo Cluster (Galaxy Cluster)"],
    value: "vir",
    info: "The Virgo constellation represents a maiden. It is one of the 48 constellations listed by the 2nd-century astronomer Ptolemy. Virgo is best visible from Earth during the spring months in the Northern Hemisphere.",
    rightAscension: "13h 00m 00.00s",
    declination: "+00° 00′ 00.0″",
    area: "1294.4 square degrees",
    imageSrc: "../images/virgo.png"
  },
  {
    name: "Volans",
    shape: "The Volans constellation represents a flying fish.",
    brightestStars: ["β Volantis", "γ Volantis", "α Volantis"],
    interestingObjects: ["Volans Dwarf (Volans Dwarf Galaxy)", "NGC 2442 (Southern Pinwheel Galaxy)"],
    value: "vol",
    info: "The Volans constellation represents a flying fish. It was introduced by the Dutch navigators Pieter Dirkszoon Keyser and Frederick de Houtman in the late 16th century. Volans is best visible from Earth during the summer months in the Southern Hemisphere.",
    rightAscension: "08h 30m 00.00s",
    declination: "-70° 00′ 00.0″",
    area: "141.4 square degrees",
    imageSrc: "../images/volans.png"
  },
  {
    name: "Vulpecula",
    shape: "The Vulpecula constellation represents a fox.",
    brightestStars: ["α Vulpeculae", "β Vulpeculae", "γ Vulpeculae"],
    interestingObjects: ["Dumbbell Nebula (Messier 27)", "Coathanger Cluster (Brocchi's Cluster)"],
    value: "vul",
    info: "The Vulpecula constellation represents a fox. It was introduced by the Polish astronomer Johannes Hevelius in the 17th century. Vulpecula is best visible from Earth during the summer and autumn months in the Northern Hemisphere.",
    rightAscension: "20h 30m 00.00s",
    declination: "+25° 00′ 00.0″",
    area: "268.0 square degrees",
    imageSrc: "../images/vulpecula.png"
  }
];